### ISSUE TITLE
Upgrade to 1.7.0 or 1.7.1 from 1.6.4 not working

### ISSUE THREAD

**Issue by maxcarpenter** [xibosignage/xibo#330]
Good Morning,

Sorry new here so not sure if I am posting in the right place. We are running Xibo 1.6.4 so I followed the instructions to backup and clone the database then delete all the files and replace with the new ones keeping the old settings.php. I browse to Xibo and login and the upgrade window comes up, completes the checks ok so I go to the next screen for database upgrade and when doing that it spits out the following error:

An error occurred running the upgrade. Please take a screen shot of this page and seek help. Statement number: 80. Error Message = [SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'backgroundImageId' at row 2]

This was using 1.7.0 I did try 1.7.1 which also gave an error not sure its the same one or not but since using HyperV after trying 1.7.1 I rolled the entire machine back to before I did anything and then tried 1.7.0 but still failed so at the moment again rolled back to 1.6.4 using HyperV snapshot.

Any advice please?

**Comment by maxcarpenter** [comment]
Ok I fixed that issue I found in the databases on eof the layouts had nothing as a background when it should of been NULL. So I fixed that one and attemped to do the upgrade again this time I am getting this error:

An error occurred running the upgrade. Please take a screen shot of this page and seek help. Statement number: 82. Error Message = [SQLSTATE[HY000]: General error: 1364 Field 'DisplayOrder' doesn't have a default value]

**Comment by dasgarner** [comment]
> Ok I fixed that issue I found in the databases on eof the layouts had nothing as a background when it should of been NULL.

Can you explain that in more detail so I can apply the fix to the next release?


The next error, I am thinking it might be this statement in `80.sql`

``` sql
UPDATE `schedule` SET DisplayOrder = (SELECT MAX(DisplayOrder) FROM `schedule_detail` WHERE schedule_detail.eventid = schedule.eventid);
```

Maybe try:
``` sql
UPDATE `schedule` SET DisplayOrder = (SELECT MAX(IFNULL(DisplayOrder, 0)) FROM `schedule_detail` WHERE schedule_detail.eventid = schedule.eventid);
```

**Comment by maxcarpenter** [comment]
Thanks for the reply.

Yeh in regards to the first problem I have two designs neither have a background and in the tabel for them on the background column one says NULL the other is blank and its the blank one that bombs out the upgrade. if I set a background it puts something in that field and it doesn't bomb out the upgrade on that step. That is how I got around it.

As for the second part I will give that ago either this afternoon or tomorrow. Thanks.

**Comment by dasgarner** [comment]
On reflection I think that should be this:

```
UPDATE `schedule` SET DisplayOrder = IFNULL((SELECT MAX(DisplayOrder) FROM `schedule_detail` WHERE schedule_detail.eventid = schedule.eventid), 0)
```

**Comment by scienceworld** [comment]
this issue persists with the patched 80.sql file as noted above.
the background column in the 1.6.4 database has values other than a number, and null.  there are some empty string rows as well.

![image](https://cloud.githubusercontent.com/assets/3997916/6447223/71b36ad6-c0c5-11e4-8c45-f90f396061a5.png)

**Comment by dasgarner** [comment]
Think I have it now! Thanks for responding.
